# Generated by Django 3.1.4 on 2020-12-23 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charityApp', '0002_auto_20201223_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='charityApp.user'),
        ),
    ]
